rm -rf ./.svn
rm -rf ./helios-jmx/.settings/.svn
rm -rf ./helios-jmx/.svn
rm -rf ./helios-jmx/src/.svn
rm -rf ./helios-jmx/src/main/.svn
rm -rf ./helios-jmx/src/main/java/.svn
rm -rf ./helios-jmx/src/main/java/org/.svn
rm -rf ./helios-jmx/src/main/java/org/helios/.svn
rm -rf ./helios-jmx/src/main/java/org/helios/helpers/.svn
rm -rf ./helios-jmx/src/main/java/org/helios/helpers/beansupport/.svn
rm -rf ./helios-jmx/src/main/java/org/helios/jmx/.svn
rm -rf ./helios-jmx/src/main/java/org/helios/jmx/client/.svn
rm -rf ./helios-jmx/src/main/java/org/helios/jmx/client/jboss/.svn
rm -rf ./helios-jmx/src/main/java/org/helios/jmx/client/local/.svn
rm -rf ./helios-jmx/src/main/java/org/helios/jmx/dynamic/.svn
rm -rf ./helios-jmx/src/main/java/org/helios/jmx/dynamic/annotations/.svn
rm -rf ./helios-jmx/src/main/java/org/helios/jmx/dynamic/annotations/asynch/.svn
rm -rf ./helios-jmx/src/main/java/org/helios/jmx/dynamic/annotations/introspection/.svn
rm -rf ./helios-jmx/src/main/java/org/helios/jmx/dynamic/annotations/options/.svn
rm -rf ./helios-jmx/src/main/java/org/helios/jmx/dynamic/classloading/.svn
rm -rf ./helios-jmx/src/main/java/org/helios/jmx/dynamic/classloading/loading/.svn
rm -rf ./helios-jmx/src/main/java/org/helios/jmx/dynamic/container/.svn
rm -rf ./helios-jmx/src/main/java/org/helios/jmx/dynamic/core/.svn
rm -rf ./helios-jmx/src/main/java/org/helios/jmx/dynamic/core/registry/.svn
rm -rf ./helios-jmx/src/main/java/org/helios/jmx/nv/.svn
rm -rf ./helios-jmx/src/main/java/org/helios/jmx/propertyeditors/.svn
rm -rf ./helios-jmx/src/main/java/org/helios/jmx/rcl/.svn
rm -rf ./helios-jmx/src/main/java/org/helios/jmx/reference/.svn
rm -rf ./helios-jmx/src/main/java/org/helios/jmx/threadservices/.svn
rm -rf ./helios-jmx/src/main/java/org/helios/jmx/threadservices/concurrency/.svn
rm -rf ./helios-jmx/src/main/java/org/helios/jmx/threadservices/dedicated/.svn
rm -rf ./helios-jmx/src/main/java/org/helios/jmx/threadservices/instrumentation/.svn
rm -rf ./helios-jmx/src/main/java/org/helios/jmx/threadservices/metrics/.svn
rm -rf ./helios-jmx/src/main/java/org/helios/jmx/threadservices/pausable/.svn
rm -rf ./helios-jmx/src/main/java/org/helios/jmx/threadservices/scheduling/.svn
rm -rf ./helios-jmx/src/main/java/org/helios/jmx/threadservices/scheduling/quartz/.svn
rm -rf ./helios-jmx/src/main/java/org/helios/jmx/threadservices/submission/.svn
rm -rf ./helios-jmx/src/main/java/org/helios/jmx/util/.svn
rm -rf ./helios-jmx/src/test/.svn
rm -rf ./helios-jmx/src/test/java/.svn
rm -rf ./helios-jmx/src/test/java/org/.svn
rm -rf ./helios-jmx/src/test/java/org/helios/.svn
rm -rf ./helios-opentrace/.svn
rm -rf ./helios-opentrace/helios-opentrace-amqp/.svn
rm -rf ./helios-opentrace/helios-opentrace-amqp/src/.svn
rm -rf ./helios-opentrace/helios-opentrace-amqp/src/main/.svn
rm -rf ./helios-opentrace/helios-opentrace-amqp/src/main/java/.svn
rm -rf ./helios-opentrace/helios-opentrace-amqp/src/main/java/org/.svn
rm -rf ./helios-opentrace/helios-opentrace-amqp/src/main/java/org/helios/.svn
rm -rf ./helios-opentrace/helios-opentrace-amqp/src/test/.svn
rm -rf ./helios-opentrace/helios-opentrace-amqp/src/test/java/.svn
rm -rf ./helios-opentrace/helios-opentrace-amqp/src/test/java/org/.svn
rm -rf ./helios-opentrace/helios-opentrace-amqp/src/test/java/org/helios/.svn
rm -rf ./helios-opentrace/helios-opentrace-core/.settings/.svn
rm -rf ./helios-opentrace/helios-opentrace-core/.svn
rm -rf ./helios-opentrace/helios-opentrace-core/src/.svn
rm -rf ./helios-opentrace/helios-opentrace-core/src/main/.svn
rm -rf ./helios-opentrace/helios-opentrace-core/src/main/java/.svn
rm -rf ./helios-opentrace/helios-opentrace-core/src/main/java/org/.svn
rm -rf ./helios-opentrace/helios-opentrace-core/src/main/java/org/helios/.svn
rm -rf ./helios-opentrace/helios-opentrace-core/src/main/java/org/helios/server/.svn
rm -rf ./helios-opentrace/helios-opentrace-core/src/main/java/org/helios/server/session/.svn
rm -rf ./helios-opentrace/helios-opentrace-core/src/main/java/org/helios/tracing/.svn
rm -rf ./helios-opentrace/helios-opentrace-core/src/main/java/org/helios/tracing/accumulator/.svn
rm -rf ./helios-opentrace/helios-opentrace-core/src/main/java/org/helios/tracing/aop/.svn
rm -rf ./helios-opentrace/helios-opentrace-core/src/main/java/org/helios/tracing/core/.svn
rm -rf ./helios-opentrace/helios-opentrace-core/src/main/java/org/helios/tracing/core/heliosquery/.svn
rm -rf ./helios-opentrace/helios-opentrace-core/src/main/java/org/helios/tracing/core/listener/.svn
rm -rf ./helios-opentrace/helios-opentrace-core/src/main/java/org/helios/tracing/core/listener/remote/.svn
rm -rf ./helios-opentrace/helios-opentrace-core/src/main/java/org/helios/tracing/core/queryservice/.svn
rm -rf ./helios-opentrace/helios-opentrace-core/src/main/java/org/helios/tracing/deltas/.svn
rm -rf ./helios-opentrace/helios-opentrace-core/src/main/java/org/helios/tracing/extended/.svn
rm -rf ./helios-opentrace/helios-opentrace-core/src/main/java/org/helios/tracing/extended/graphite/.svn
rm -rf ./helios-opentrace/helios-opentrace-core/src/main/java/org/helios/tracing/extended/introscope/.svn
rm -rf ./helios-opentrace/helios-opentrace-core/src/main/java/org/helios/tracing/extended/logging/.svn
rm -rf ./helios-opentrace/helios-opentrace-core/src/main/java/org/helios/tracing/instrumentation/.svn
rm -rf ./helios-opentrace/helios-opentrace-core/src/main/java/org/helios/tracing/interval/.svn
rm -rf ./helios-opentrace/helios-opentrace-core/src/main/java/org/helios/tracing/jmx/.svn
rm -rf ./helios-opentrace/helios-opentrace-core/src/main/java/org/helios/tracing/jmx/openmbean/.svn
rm -rf ./helios-opentrace/helios-opentrace-core/src/main/java/org/helios/tracing/lifecycle/.svn
rm -rf ./helios-opentrace/helios-opentrace-core/src/main/java/org/helios/tracing/nulltracer/.svn
rm -rf ./helios-opentrace/helios-opentrace-core/src/main/java/org/helios/tracing/otm/.svn
rm -rf ./helios-opentrace/helios-opentrace-core/src/main/java/org/helios/tracing/queues/.svn
rm -rf ./helios-opentrace/helios-opentrace-core/src/main/java/org/helios/tracing/stack/.svn
rm -rf ./helios-opentrace/helios-opentrace-core/src/main/java/org/helios/tracing/thread/.svn
rm -rf ./helios-opentrace/helios-opentrace-core/src/main/java/org/helios/tracing/types/.svn
rm -rf ./helios-opentrace/helios-opentrace-core/src/main/java/org/helios/tracing/userlocator/.svn
rm -rf ./helios-opentrace/helios-opentrace-core/src/main/java/org/helios/tracing/util/.svn
rm -rf ./helios-opentrace/helios-opentrace-core/src/test/.svn
rm -rf ./helios-opentrace/helios-opentrace-core/src/test/java/.svn
rm -rf ./helios-opentrace/helios-opentrace-core/src/test/java/org/.svn
rm -rf ./helios-opentrace/helios-opentrace-core/src/test/java/org/helios/.svn
rm -rf ./helios-opentrace/helios-opentrace-esper/.svn
rm -rf ./helios-opentrace/helios-opentrace-esper/src/.svn
rm -rf ./helios-opentrace/helios-opentrace-esper/src/main/.svn
rm -rf ./helios-opentrace/helios-opentrace-esper/src/main/java/.svn
rm -rf ./helios-opentrace/helios-opentrace-esper/src/main/java/org/.svn
rm -rf ./helios-opentrace/helios-opentrace-esper/src/main/java/org/helios/.svn
rm -rf ./helios-opentrace/helios-opentrace-esper/src/test/.svn
rm -rf ./helios-opentrace/helios-opentrace-esper/src/test/java/.svn
rm -rf ./helios-opentrace/helios-opentrace-esper/src/test/java/org/.svn
rm -rf ./helios-opentrace/helios-opentrace-esper/src/test/java/org/helios/.svn
rm -rf ./helios-opentrace/helios-opentrace-relay/.svn
rm -rf ./helios-opentrace/helios-opentrace-relay/src/.svn
rm -rf ./helios-opentrace/helios-opentrace-relay/src/main/.svn
rm -rf ./helios-opentrace/helios-opentrace-relay/src/main/java/.svn
rm -rf ./helios-opentrace/helios-opentrace-relay/src/main/java/org/.svn
rm -rf ./helios-opentrace/helios-opentrace-relay/src/main/java/org/helios/.svn
rm -rf ./helios-opentrace/helios-opentrace-relay/src/test/.svn
rm -rf ./helios-opentrace/helios-opentrace-relay/src/test/java/.svn
rm -rf ./helios-opentrace/helios-opentrace-relay/src/test/java/org/.svn
rm -rf ./helios-opentrace/helios-opentrace-relay/src/test/java/org/helios/.svn
rm -rf ./helios-opentrace/src/.svn
rm -rf ./helios-opentrace/src/main/.svn
rm -rf ./helios-opentrace/src/main/java/.svn
rm -rf ./helios-opentrace/src/main/java/org/.svn
rm -rf ./helios-opentrace/src/main/java/org/helios/.svn
rm -rf ./helios-opentrace/src/test/.svn
rm -rf ./helios-opentrace/src/test/java/.svn
rm -rf ./helios-opentrace/src/test/java/org/.svn
rm -rf ./helios-opentrace/src/test/java/org/helios/.svn
rm -rf ./helios-spring/.svn
rm -rf ./helios-spring/helios-spring-core/.svn
rm -rf ./helios-spring/helios-spring-core/src/.svn
rm -rf ./helios-spring/helios-spring-core/src/main/.svn
rm -rf ./helios-spring/helios-spring-core/src/main/java/.svn
rm -rf ./helios-spring/helios-spring-core/src/main/java/org/.svn
rm -rf ./helios-spring/helios-spring-core/src/main/java/org/helios/.svn
rm -rf ./helios-spring/helios-spring-core/src/main/java/org/helios/io/.svn
rm -rf ./helios-spring/helios-spring-core/src/main/java/org/helios/io/file/.svn
rm -rf ./helios-spring/helios-spring-core/src/main/java/org/helios/io/file/filters/.svn
rm -rf ./helios-spring/helios-spring-core/src/main/java/org/helios/io/file/jurl/.svn
rm -rf ./helios-spring/helios-spring-core/src/main/java/org/helios/spring/.svn
rm -rf ./helios-spring/helios-spring-core/src/main/java/org/helios/spring/container/.svn
rm -rf ./helios-spring/helios-spring-core/src/main/java/org/helios/spring/container/jmx/.svn
rm -rf ./helios-spring/helios-spring-core/src/main/java/org/helios/spring/container/templates/.svn
rm -rf ./helios-spring/helios-spring-core/src/main/java/org/helios/spring/container/templates/hibernate/.svn
rm -rf ./helios-spring/helios-spring-core/src/main/java/org/helios/spring/container/templates/merging/.svn
rm -rf ./helios-spring/helios-spring-core/src/main/java/org/helios/spring/container/templates/provider/.svn
rm -rf ./helios-spring/helios-spring-core/src/main/java/org/helios/spring/container/templates/provider/persistence/.svn
rm -rf ./helios-spring/helios-spring-core/src/main/java/org/helios/spring/jmx/.svn
rm -rf ./helios-spring/helios-spring-core/src/main/java/org/helios/spring/monitors/.svn
rm -rf ./helios-spring/helios-spring-core/src/main/java/org/json/.svn
rm -rf ./helios-spring/helios-spring-core/src/test/.svn
rm -rf ./helios-spring/helios-spring-core/src/test/java/.svn
rm -rf ./helios-spring/helios-spring-core/src/test/java/org/.svn
rm -rf ./helios-spring/helios-spring-core/src/test/java/org/helios/.svn
rm -rf ./helios-spring/helios-spring-launcher/.svn
rm -rf ./helios-spring/helios-spring-launcher/src/.svn
rm -rf ./helios-spring/helios-spring-launcher/src/main/.svn
rm -rf ./helios-spring/helios-spring-launcher/src/main/assembly/.svn
rm -rf ./helios-spring/helios-spring-launcher/src/main/java/.svn
rm -rf ./helios-spring/helios-spring-launcher/src/main/java/org/.svn
rm -rf ./helios-spring/helios-spring-launcher/src/main/java/org/helios/.svn
rm -rf ./helios-spring/helios-spring-launcher/src/test/.svn
rm -rf ./helios-spring/helios-spring-launcher/src/test/java/.svn
rm -rf ./helios-spring/helios-spring-launcher/src/test/java/org/.svn
rm -rf ./helios-spring/helios-spring-launcher/src/test/java/org/helios/.svn
rm -rf ./helios-spring/src/.svn
rm -rf ./helios-spring/src/main/.svn
rm -rf ./helios-spring/src/main/java/.svn
rm -rf ./helios-spring/src/main/java/org/.svn
rm -rf ./helios-spring/src/main/java/org/helios/.svn
rm -rf ./helios-spring/src/test/.svn
rm -rf ./helios-spring/src/test/java/.svn
rm -rf ./helios-spring/src/test/java/org/.svn
rm -rf ./helios-spring/src/test/java/org/helios/.svn
rm -rf ./helios-util/.settings/.svn
rm -rf ./helios-util/.svn
rm -rf ./helios-util/src/.svn
rm -rf ./helios-util/src/main/.svn
rm -rf ./helios-util/src/main/java/.svn
rm -rf ./helios-util/src/main/java/org/.svn
rm -rf ./helios-util/src/main/java/org/helios/.svn
rm -rf ./helios-util/src/main/java/org/helios/aop/.svn
rm -rf ./helios-util/src/main/java/org/helios/cache/.svn
rm -rf ./helios-util/src/main/java/org/helios/cache/softref/.svn
rm -rf ./helios-util/src/main/java/org/helios/console/.svn
rm -rf ./helios-util/src/main/java/org/helios/containers/.svn
rm -rf ./helios-util/src/main/java/org/helios/containers/buckets/.svn
rm -rf ./helios-util/src/main/java/org/helios/containers/counters/.svn
rm -rf ./helios-util/src/main/java/org/helios/editors/.svn
rm -rf ./helios-util/src/main/java/org/helios/enums/.svn
rm -rf ./helios-util/src/main/java/org/helios/helpers/.svn
rm -rf ./helios-util/src/main/java/org/helios/helpers/classext/.svn
rm -rf ./helios-util/src/main/java/org/helios/helpers/counters/.svn
rm -rf ./helios-util/src/main/java/org/helios/io/.svn
rm -rf ./helios-util/src/main/java/org/helios/io/file/.svn
rm -rf ./helios-util/src/main/java/org/helios/io/file/filters/.svn
rm -rf ./helios-util/src/main/java/org/helios/logging/.svn
rm -rf ./helios-util/src/main/java/org/helios/logging/appenders/.svn
rm -rf ./helios-util/src/main/java/org/helios/reflection/.svn
rm -rf ./helios-util/src/main/java/org/helios/version/.svn
rm -rf ./helios-util/src/test/.svn
rm -rf ./helios-util/src/test/java/.svn
rm -rf ./helios-util/src/test/java/org/.svn
rm -rf ./helios-util/src/test/java/org/helios/.svn
rm -rf ./src/.svn
rm -rf ./src/main/.svn
rm -rf ./src/main/java/.svn
rm -rf ./src/main/java/org/.svn
rm -rf ./src/main/java/org/helios/.svn
rm -rf ./src/test/.svn
rm -rf ./src/test/java/.svn
rm -rf ./src/test/java/org/.svn
rm -rf ./src/test/java/org/helios/.svn
