package org.helios.spring.container.templates.provider.persistence;

// Generated Sep 4, 2009 3:51:26 PM by Hibernate Tools 3.2.4.GA

import java.util.HashSet;
import java.util.Set;
import java.util.concurrent.atomic.AtomicInteger;

/**
 * Provision generated by hbm2java
 */
public class Provision implements java.io.Serializable {

	private int provisionId;
	private String provisionName;
	private Set<ProvisionSet> provisionSets = new HashSet<ProvisionSet>(0);
	protected static final AtomicInteger serial = new AtomicInteger(0);

	public Provision() {
	}

	public Provision(int provisionId, String provisionName) {
		this.provisionId = provisionId;
		this.provisionName = provisionName;
	}

	public Provision(int provisionId, String provisionName,
			Set<ProvisionSet> provisionSets) {
		this.provisionId = provisionId;
		this.provisionName = provisionName;
		this.provisionSets = provisionSets;
	}
	
	/**
	 * For non-DB
	 * @param provisionName
	 * @param provisionSets
	 */
	public Provision(String provisionName,Set<ProvisionSet> provisionSets) {
		this.provisionId = serial.incrementAndGet();
		this.provisionName = provisionName;
		this.provisionSets = provisionSets;
	}
	

	public int getProvisionId() {
		return this.provisionId;
	}

	public void setProvisionId(int provisionId) {
		this.provisionId = provisionId;
	}

	public String getProvisionName() {
		return this.provisionName;
	}

	public void setProvisionName(String provisionName) {
		this.provisionName = provisionName;
	}

	public Set<ProvisionSet> getProvisionSets() {
		return this.provisionSets;
	}

	public void setProvisionSets(Set<ProvisionSet> provisionSets) {
		this.provisionSets = provisionSets;
	}

}
