package org.helios.spring.container.templates.hibernate;

// Generated Oct 14, 2008 9:08:52 AM by Hibernate Tools 3.2.0.CR1

/**
 * Ctor generated by hbm2java
 */
public class Ctor implements java.io.Serializable {


	private static final long serialVersionUID = 6998195782912344520L;
	private int ctorId;
	private Bean bean;
	private int sequence;
	private String value;
	private boolean ref;

	public Ctor() {
	}

	public Ctor(int ctorId, Bean bean, int sequence, String value, boolean ref) {
		this.ctorId = ctorId;
		this.bean = bean;
		this.sequence = sequence;
		this.value = value;
		this.ref = ref;
	}

	public int getCtorId() {
		return this.ctorId;
	}

	public void setCtorId(int ctorId) {
		this.ctorId = ctorId;
	}

	public Bean getBean() {
		return this.bean;
	}

	public void setBean(Bean bean) {
		this.bean = bean;
	}

	public int getSequence() {
		return this.sequence;
	}

	public void setSequence(int sequence) {
		this.sequence = sequence;
	}

	public String getValue() {
		return this.value;
	}

	public void setValue(String value) {
		this.value = value;
	}

	public boolean isRef() {
		return this.ref;
	}

	public void setRef(boolean ref) {
		this.ref = ref;
	}

	/**
	 * Constructs a <code>String</code> with all attributes
	 * in name = value format.
	 *
	 * @return a <code>String</code> representation 
	 * of this object.
	 */
	public String toString()
	{
	    final String CR = "\n\t";
	
	    StringBuilder retValue = new StringBuilder();
	    
	    retValue.append("Ctor ( ")	        
	        .append(CR).append("ctorId:").append(this.ctorId)	        
	        .append(CR).append("sequence:").append(this.sequence)
	        .append(CR).append("value:").append(this.value)
	        .append(CR).append("ref:").append(this.ref)
	        .append("\n )");
	    
	    return retValue.toString();
	}
	
	

}
