package org.helios.spring.container.templates.hibernate;

// Generated Oct 14, 2008 9:08:52 AM by Hibernate Tools 3.2.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * Merger generated by hbm2java
 */
public class Merger implements java.io.Serializable {

	private static final long serialVersionUID = 6749249255296322582L;
	private int mergerId;
	private String classType;
	private String className;
	private Set<MergerBean> mergerBeans = new HashSet<MergerBean>(0);

	public Merger() {
	}

	public Merger(int mergerId, String classType, String className) {
		this.mergerId = mergerId;
		this.classType = classType;
		this.className = className;
	}

	public Merger(int mergerId, String classType, String className,
			Set<MergerBean> mergerBeans) {
		this.mergerId = mergerId;
		this.classType = classType;
		this.className = className;
		this.mergerBeans = mergerBeans;
	}

	public int getMergerId() {
		return this.mergerId;
	}

	public void setMergerId(int mergerId) {
		this.mergerId = mergerId;
	}

	public String getClassType() {
		return this.classType;
	}

	public void setClassType(String classType) {
		this.classType = classType;
	}

	public String getClassName() {
		return this.className;
	}

	public void setClassName(String className) {
		this.className = className;
	}

	public Set<MergerBean> getMergerBeans() {
		return this.mergerBeans;
	}

	public void setMergerBeans(Set<MergerBean> mergerBeans) {
		this.mergerBeans = mergerBeans;
	}

	/**
	 * Constructs a <code>String</code> with all attributes
	 * in name = value format.
	 *
	 * @return a <code>String</code> representation 
	 * of this object.
	 */
	public String toString()
	{
	    final String CR = "\n\t";
	    final String CRR = "\n\t\t";
	
	    StringBuilder retValue = new StringBuilder();
	    
	    retValue.append("Merger ( ")
	        .append(CR).append("mergerId:").append(this.mergerId)
	        .append(CR).append("classType:").append(this.classType)
	        .append(CR).append("className:").append(this.className)
	        .append("\n)");
	    
	    return retValue.toString();
	}
	
	

}
