package org.helios.spring.container.templates.hibernate;

// Generated Oct 14, 2008 9:08:52 AM by Hibernate Tools 3.2.0.CR1

/**
 * Property generated by hbm2java
 */
public class Property implements java.io.Serializable {

	private static final long serialVersionUID = 2404308209497765300L;
	private int propertyId;
	private Bean bean;
	private String name;
	private String value;
	private boolean ref;

	public Property() {
	}

	public Property(int propertyId, Bean bean, String name, String value,
			boolean ref) {
		this.propertyId = propertyId;
		this.bean = bean;
		this.name = name;
		this.value = value;
		this.ref = ref;
	}

	public int getPropertyId() {
		return this.propertyId;
	}

	public void setPropertyId(int propertyId) {
		this.propertyId = propertyId;
	}

	public Bean getBean() {
		return this.bean;
	}

	public void setBean(Bean bean) {
		this.bean = bean;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getValue() {
		return this.value;
	}

	public void setValue(String value) {
		this.value = value;
	}

	public boolean isRef() {
		return this.ref;
	}

	public void setRef(boolean ref) {
		this.ref = ref;
	}

	/**
	 * Constructs a <code>String</code> with all attributes
	 * in name = value format.
	 *
	 * @return a <code>String</code> representation 
	 * of this object.
	 */
	public String toString()
	{
	    final String CR = "\n\t";
	
	    StringBuilder retValue = new StringBuilder();
	    
	    retValue.append("Property ( ")
	        .append(CR).append("propertyId:").append(this.propertyId)
	        .append(CR).append("name:").append(this.name)
	        .append(CR).append("value:").append(this.value)
	        .append(CR).append("ref:").append(this.ref)
	        .append("\n )");
	    
	    return retValue.toString();
	}
	

}
